apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      name: api
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
      - name: api
        image: artifacts.developer.gov.bc.ca/af3c-gen-docker-local/api:latest
---         
apiVersion: route.openshift.io/v1
kind: Route
metadata:
    name: api
spec:
  host: jobstore-api.apps.silver.devops.gov.bc.ca