apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: nestjs-app
spec:
  triggers:
      - imageChangeParams:
          from:
            kind: ImageStreamTag
            name: api:latest
            namespace: f3c07a-tools
          type: ImageChange
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
    name: nestjs-app
spec:
  host: pjs-api.digital.gov.bc.ca
