version: '3.8'

services:
  db:
    image: postgres:16
    user: postgres
    container_name: db
    hostname: db
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-api}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres:/var/lib/postgresql/data:delegated
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # nestjs-app:
  #   env_file:
  #       - .env
  #   build:
  #     context: .
  #     # image: pjs-frontend:18-alpine
  #     dockerfile: apps/api/Dockerfile.dev
  #     args:
  #       - POSTGRES_DB=${POSTGRES_DB}
  #       - POSTGRES_USER=${POSTGRES_USER}
  #       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #       - DATABASE_URL=${DATABASE_URL}
  #       - KEYCLOAK_REALM_URL=${KEYCLOAK_REALM_URL}
  #       - KEYCLOAK_CLIENT_ID_PRIVATE=${KEYCLOAK_CLIENT_ID_PRIVATE}
  #       - KEYCLOAK_CLIENT_ID_PUBLIC=${KEYCLOAK_CLIENT_ID_PUBLIC}
  #       - KEYCLOAK_REDIRECT_URL=${VITE_KEYCLOAK_REDIRECT_URL}
  #       - BI_URL=${BI_URL}
  #       - BI_USERNAME=${BI_USERNAME}
  #       - BI_PASSWORD=${BI_PASSWORD}
  #       - ELASTIC_NODE=${ELASTIC_NODE}
  #       - ELASTIC_USERNAME=${ELASTIC_USERNAME}
  #       - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
  #       - PEOPLESOFT_URL=${PEOPLESOFT_URL}
  #       - PEOPLESOFT_USERNAME=${PEOPLESOFT_USERNAME}
  #       - PEOPLESOFT_PASSWORD=${PEOPLESOFT_PASSWORD}
  #       - CRM_APPLICATION_CONTEXT=${CRM_APPLICATION_CONTEXT}
  #       - CRM_PASSWORD=${CRM_PASSWORD}
  #       - CRM_URL=${CRM_URL}
  #       - CRM_USERNAME=${CRM_USERNAME}
  #   ports:
  #     - 4000:4000
  #   depends_on:
  #     db:
  #       condition: service_started
  #   volumes:
  #     - ./apps/api/src:/usr/src/app/src:cached
  #     - ./apps/api/prisma:/usr/src/app/prisma
  #     - api-nodemodules:/node_modules


  # # http://localhost:5173/
  # vite_docker:
  #   build:
  #     context: .
  #     dockerfile: apps/app/Dockerfile
  #     args:
  #       - VITE_BACKEND_URL=${VITE_BACKEND_URL}
  #       - VITE_KEYCLOAK_REALM_URL=${VITE_KEYCLOAK_REALM_URL}
  #       - VITE_KEYCLOAK_CLIENT_ID=${VITE_KEYCLOAK_CLIENT_ID}
  #       - VITE_KEYCLOAK_REDIRECT_URL=${VITE_KEYCLOAK_REDIRECT_URL}
  #   ports:
  #     - 5173:5173
  #   volumes:
  #     - ./src:/usr/src/app/src:cached


  cypress:
    image: cypress/included:13.4.0
    container_name: cypress
    hostname: cypress
    # ports:
    #   - 5432:5432
    env_file:
      - .env
    volumes:
      - ./apps/app/cypress:/e2e:cached
      - ./apps/app/nodemodules:/node_modules:cached

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    # 8.x
    environment:
      [
        'ELASTIC_PASSWORD=${ELASTIC_PASSWORD}',
        'CLI_JAVA_OPTS=-Xms2g -Xmx2g',
        'bootstrap.memory_lock=true',
        'discovery.type=single-node',
        'xpack.security.enabled=false',
        'xpack.security.enrollment.enabled=false'
      ]
    ports:
      - 9200:9200
    networks:
      - psa-job-store
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '2.0'
        reservations:
          cpus: '1.0'

# services:
#   nestjs-app:
#     env_file:
#         - .env
#     build:
#       context: .
#       image: pjs-frontend:18-alpine
#       dockerfile: apps/api/Dockerfile.dev
#       args:
#         - POSTGRES_DB=${POSTGRES_DB}
#         - POSTGRES_USER=${POSTGRES_USER}
#         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#         - DATABASE_URL=${DATABASE_URL}
#         - KEYCLOAK_REALM_URL=${KEYCLOAK_REALM_URL}
#         - KEYCLOAK_CLIENT_ID_PRIVATE=${KEYCLOAK_CLIENT_ID_PRIVATE}
#         - KEYCLOAK_CLIENT_ID_PUBLIC=${KEYCLOAK_CLIENT_ID_PUBLIC}
#         - KEYCLOAK_REDIRECT_URL=${KEYCLOAK_REDIRECT_URL}
#     ports:
#       - 4000:4000
#     depends_on:
#       db:
#         condition: service_started
#     volumes:
#       - ./apps/api/src:/usr/src/app/src:cached
#       - ./apps/api/prisma:/usr/src/app/prisma
#       - api-nodemodules:/node_modules
#     networks:
#       - psa-job-store



#   # http://localhost:5173/
#   vite_docker:
#     build:
#       context: .
#       dockerfile: apps/app/Dockerfile
#       args:
#         - VITE_BACKEND_URL=${VITE_BACKEND_URL}
#         - VITE_KEYCLOAK_REALM_URL=${VITE_KEYCLOAK_REALM_URL}
#         - VITE_KEYCLOAK_CLIENT_ID=${VITE_KEYCLOAK_CLIENT_ID}
#         - VITE_KEYCLOAK_REDIRECT_URL=${VITE_KEYCLOAK_REDIRECT_URL}
#     ports:
#       - 5173:5173
#     volumes:
#       - ./src:/usr/src/app/src:cached
#     networks:
#       - psa-job-store

networks:
  pjs-elastic:
    name: pjs-elastic
  psa-job-store:
    name: psa-job-store

volumes:
  postgres:
  api-nodemodules:
