apiVersion: v1
kind: ConfigMap
metadata:
  name: fider-postgres-initdb
data:
  init-extension.sh: |
    #!/bin/bash
    echo "Creating pg_trgm extension..."
    psql -U postgres  -c "CREATE DATABASE IF NOT EXISTS $POSTGRESQL_DATABASE;"
    psql -U postgres -d $POSTGRESQL_DATABASE -c "CREATE EXTENSION IF NOT EXISTS pg_trgm;"