kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: nginx-secrets
  annotations:
    openshift.io/display-name:  nginx secrets
    description: Secrets templates psa job store application
    tags: pjs

parameters:
  - name: CLIENT_ID
    displayName: "Client ID"
    description: "Keycloak Client ID"
    required: true
    value: ""
  - name: CLIENT_SECRET
    displayName: "Client Secret"
    description: "Keycloak Client secret"
    required: true
    value: ""
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: nginx-secrets
    stringData:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    