kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: secrets
  annotations:
    openshift.io/display-name:  Secrets templates psa job store application
    description: Secrets templates psa job store application
    tags: pjs

parameters:
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "f3c07a"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "dev"
  - name: NODE_ENV
    displayName: "Environment name"
    description: "The NODE_ENV value"
    required: true
    value: "development"
  - name: KEYCLOAK_REALM_URL
    displayName: "Keycloak URL"
    description: "The URL for Keycloak"
    required: true
    value: ""
  - name: POSTGRES_DB
    displayName: "POSTGRES_DB"
    description: "The URL for the postgres db"
    generate: expression
    from: "[a-zA-Z0-9]{16}"
  - name: POSTGRES_USER
    displayName: "POSTGRES_USER"
    description: "The URL for the postgres db"
    generate: expression
    from: "[a-z]{16}"
  - name: POSTGRES_PASSWORD
    displayName: "POSTGRES_PASSWORD"
    description: "The database regular account password."
    generate: expression
    from: "[a-zA-Z0-9]{32}"
  - name: POSTGRES_ADMIN_PASSWORD
    displayName: "POSTGRES_ADMIN_PASSWORD"
    description: "The database regular account password."
    generate: expression
    from: "[a-zA-Z0-9]{32}"
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: secrets
    stringData:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@api-postgres:5432/${POSTGRES_DB}
      KEYCLOAK_REALM_URL: ${KEYCLOAK_REALM_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
