kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: secrets
  annotations:
    openshift.io/display-name:  Secrets templates psa job store application
    description: Secrets templates psa job store application
    tags: pjs

parameters:
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "f3c07a"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "dev"
  - name: NODE_ENV
    displayName: "Environment name"
    description: "The NODE_ENV value"
    required: true
    value: "development"
  - name: KEYCLOAK_API_URL
    displayName: "Keycloak API URL"
    description: ""
    required: true
    value: ""
  - name: KEYCLOAK_API_TOKEN_URL
    displayName: "Production API Token URL"
    description: ""
    required: true
    value: ""
  - name: KEYCLOAK_API_ENVIRONMENT
    displayName: "Keycloak API Environment"
    description: "The name for this environment [dev, test, prod]"
    required: true
    value: ""
  - name: KEYCLOAK_API_INTEGRATION_ID
    displayName: "Keycloak API Integration ID"
    description: "The numeric ID of the OIDC client"
    required: true
    value: ""
  - name: KEYCLOAK_API_SERVICE_ACCOUNT_CLIENT_ID
    displayName: "Keycloak API Service Account Client ID"
    description: ""
    required: true
    value: ""
  - name: KEYCLOAK_API_SERVICE_ACCOUNT_CLIENT_SECRET
    displayName: "Keycloak API Service Account Client Secret"
    description: ""
    required: true
    value: ""
  - name: KEYCLOAK_REALM_URL
    displayName: "Keycloak URL"
    description: "The URL for Keycloak"
    required: true
    value: ""
  - name: KEYCLOAK_CLIENT_ID_PRIVATE
    displayName: "Keycloak Private Client ID"
    description: ""
    required: true
    value: ""
  - name: KEYCLOAK_CLIENT_ID_PUBLIC
    displayName: "Keycloak Private Client ID"
    description: ""
    required: true
    value: ""
  - name: POSTGRES_DB
    displayName: "POSTGRES_DB"
    description: "The URL for the postgres db"
    generate: expression
    from: "[a-zA-Z0-9]{16}"
  - name: POSTGRES_USER
    displayName: "POSTGRES_USER"
    description: "The URL for the postgres db"
    generate: expression
    from: "[a-z]{16}"
  - name: POSTGRES_PASSWORD
    displayName: "POSTGRES_PASSWORD"
    description: "The database regular account password."
    generate: expression
    from: "[a-zA-Z0-9]{32}"
  - name: POSTGRES_ADMIN_PASSWORD
    displayName: "POSTGRES_ADMIN_PASSWORD"
    description: "The database regular account password."
    generate: expression
    from: "[a-zA-Z0-9]{32}"
  - name: ELASTIC_PASSWORD
    displayName: "ELASTIC_PASSWORD"
    description: "The elasticsearch regular account password."
    required: true
    value: "password"
  - name: ELASTIC_USERNAME
    displayName: "ELASTIC_USERNAME"
    description: "The elasticsearch regular account username."
    required: true
    value: ""
  - name: ELASTIC_NODE
    displayName: "ELASTIC_NODE"
    description: "The URL for elasticsearch."
    required: true
    value: "http://elasticsearch:9200"
  - name: PEOPLESOFT_PASSWORD
    displayName: "PEOPLESOFT_PASSWORD"
    description: "The peoplesoft regular account password."
    required: true
    value: "password"
  - name: PEOPLESOFT_USERNAME
    displayName: "PEOPLESOFT_USERNAME"
    description: "The peoplesoft regular account username."
    required: true
    value: ""
  - name: PEOPLESOFT_URL
    displayName: "PEOPLESOFT_URL"
    description: "The URL for peoplesoft."
    required: true
    value: "http://peoplesoft:9200"
  - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
    displayName: "XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY"
    description: "Kibana Encryption Key"
    required: true
    value: ""
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: secrets
    stringData:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@api-postgres:5432/${POSTGRES_DB}
      KEYCLOAK_API_URL: ${KEYCLOAK_API_URL}
      KEYCLOAK_API_TOKEN_URL: ${KEYCLOAK_API_TOKEN_URL}
      KEYCLOAK_API_ENVIRONMENT: ${KEYCLOAK_API_ENVIRONMENT}
      KEYCLOAK_API_INTEGRATION_ID: ${KEYCLOAK_API_INTEGRATION_ID}
      KEYCLOAK_API_SERVICE_ACCOUNT_CLIENT_ID: ${KEYCLOAK_API_SERVICE_ACCOUNT_CLIENT_ID}
      KEYCLOAK_API_SERVICE_ACCOUNT_CLIENT_SECRET: ${KEYCLOAK_API_SERVICE_ACCOUNT_CLIENT_SECRET}
      KEYCLOAK_REALM_URL: ${KEYCLOAK_REALM_URL}
      KEYCLOAK_CLIENT_ID_PRIVATE: ${KEYCLOAK_CLIENT_ID_PRIVATE}
      KEYCLOAK_CLIENT_ID_PUBLIC: ${KEYCLOAK_CLIENT_ID_PUBLIC}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_NODE: ${ELASTIC_NODE}
      PEOPLESOFT_PASSWORD: ${PEOPLESOFT_PASSWORD}
      PEOPLESOFT_USERNAME: ${PEOPLESOFT_USERNAME}
      PEOPLESOFT_NODE: ${PEOPLESOFT_NODE}
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: ${XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY}
