export enum FilterOperator {
  // BigInt
  BigIntEquals = 'bi.eq',
  BigIntIn = 'bi.in',
  BigIntLt = 'bi.lt',
  BigIntLte = 'bi.lte',
  BigIntGt = 'bi.gt',
  BigIntGte = 'bi.gte',
  BigIntNotEquals = '!bi.eq',
  BigIntNotIn = '!bi.in',
  BigIntNotLt = '!bi.lt',
  BigIntNotLte = '!bi.lte',
  BigIntNotGt = '!bi.gt',
  BigIntNotGte = '!bi.gte',

  // BigIntList
  BigIntListEquals = 'bil.eq',
  BigIntListHas = 'bil.h',
  BigIntListHasEvery = 'bil.he',
  BigIntListHasSome = 'bil.hs',
  BigIntListIsEmpty = 'bil.mte',

  // Bool
  BoolEquals = 'b.eq',
  BoolNotEquals = '!b.eq',

  // BoolList
  BoolListEquals = 'bl.eq',
  BoolListHas = 'bl.h',
  BoolListHasEvery = 'bl.he',
  BoolListHasSome = 'bl.hs',
  BoolListIsEmpty = 'bl.mte',

  // DateTime
  DateTimeEquals = 'dt.eq',
  DateTimeIn = 'dt.in',
  DateTimeLt = 'dt.lt',
  DateTimeLte = 'dt.lte',
  DateTimeGt = 'dt.gt',
  DateTimeGte = 'dt.gte',
  DateTimeNotEquals = '!dt.eq',
  DateTimeNotIn = '!dt.in',
  DateTimeNotLt = '!dt.lt',
  DateTimeNotLte = '!dt.lte',
  DateTimeNotGt = '!dt.gt',
  DateTimeNotGte = '!dt.gte',

  // DateTimeList
  DateTimeListEquals = 'dtl.eq',
  DateTimeListHas = 'dtl.h',
  DateTimeListHasEvery = 'dtl.he',
  DateTimeListHasSome = 'dtl.hs',
  DateTimeListIsEmpty = 'dtl.mte',

  // Decimal
  DecimalEquals = 'dc.eq',
  DecimalIn = 'dc.in',
  DecimalLt = 'dc.lt',
  DecimalLte = 'dc.lte',
  DecimalGt = 'dc.gt',
  DecimalGte = 'dc.gte',
  DecimalNotEquals = '!dc.eq',
  DecimalNotIn = '!dc.in',
  DecimalNotLt = '!dc.lt',
  DecimalNotLte = '!dc.lte',
  DecimalNotGt = '!dc.gt',
  DecimalNotGte = '!dc.gte',

  // DecimalList
  DecimalListEquals = 'dcl.eq',
  DecimalListHas = 'dcl.h',
  DecimalListHasEvery = 'dcl.he',
  DecimalListHasSome = 'dcl.hs',
  DecimalListIsEmpty = 'dcl.mte',

  //Enum
  EnumEquals = 'e.eq',
  EnumIn = 'e.in',
  // Float
  FloatEquals = 'f.eq',
  FloatIn = 'f.in',
  FloatLt = 'f.lt',
  FloatLte = 'f.lte',
  FloatGt = 'f.gt',
  FloatGte = 'f.gte',
  FloatNotEquals = '!f.eq',
  FloatNotIn = '!f.in',
  FloatNotLt = '!f.lt',
  FloatNotLte = '!f.lte',
  FloatNotGt = '!f.gt',
  FloatNotGte = '!f.gte',

  // FloatList
  FloatListEquals = 'fl.eq',
  FloatListHas = 'fl.h',
  FloatListHasEvery = 'fl.he',
  FloatListHasSome = 'fl.hs',
  FloatListIsEmpty = 'fl.mte',

  // Int
  IntEquals = 'i.eq',
  IntIn = 'i.in',
  IntLt = 'i.lt',
  IntLte = 'i.lte',
  IntGt = 'i.gt',
  IntGte = 'i.gte',
  IntNotEquals = '!i.eq',
  IntNotIn = '!i.in',
  IntNotLt = '!i.lt',
  IntNotLte = '!i.lte',
  IntNotGt = '!i.gt',
  IntNotGte = '!i.gte',

  // IntList
  IntListEquals = 'il.eq',
  IntListHas = 'il.h',
  IntListHasEvery = 'il.he',
  IntListHasSome = 'il.hs',
  IntListIsEmpty = 'il.mte',

  // Json
  JsonEquals = 'j.eq',
  JsonStringContains = 'j.sc',
  JsonStringStartsWith = 'j.ssw',
  JsonStringEndsWith = 'j.sew',
  JsonArrayContains = 'j.ac',
  JsonArrayStartsWith = 'j.asw',
  JsonArrayEndsWith = 'j.aew',
  JsonLt = 'j.lt',
  JsonLte = 'j.lte',
  JsonGt = 'j.gt',
  JsonGte = 'j.gte',

  // JsonList
  JsonListEquals = 'jl.eq',
  JsonListHas = '.jl.h',
  JsonListHasEvery = 'jl.he',
  JsonListHasSome = 'jl.hs',
  JsonListIsEmpty = 'jl.mte',

  // String
  StringEquals = 's.eq',
  StringIn = 's.in',
  StringLt = 's.lt',
  StringLte = 's.lte',
  StringGt = 's.gt',
  StringGte = 's.gte',
  StringContains = 's.c',
  StringStartsWith = 's.sw',
  StringEndsWith = 's.ew',
  StringSearch = 's.s',
  StringIEquals = 's.eq.i',
  StringIIn = 's.in.i',
  StringILt = 's.lt.i',
  StringILte = 's.lte.i',
  StringIGt = 's.gt.i',
  StringIGte = 's.gte.i',
  StringIContains = 's.c.i',
  StringIStartsWith = 's.sw.i',
  StringIEndsWith = 's.ew.i',
  StringISearch = 's.s.i',
  StringNotEquals = '!s.eq',
  StringNotIn = '!s.in',
  StringNotLt = '!s.lt',
  StringNotLte = '!s.lte',
  StringNotGt = '!s.gt',
  StringNotGte = '!s.gte',
  StringNotContains = '!s.c',
  StringNotStartsWith = '!s.sw',
  StringNotEndsWith = '!s.ew',
  StringNotSearch = '!s.s',
  StringNotIEquals = '!s.eq.i',
  StringNotIIn = '!s.in.i',
  StringNotILt = '!s.lt.i',
  StringNotILte = '!s.lte.i',
  StringNotIGt = '!s.gt.i',
  StringNotIGte = '!s.gte.i',
  StringNotIContains = '!s.c.i',
  StringNotIStartsWith = '!s.sw.i',
  StringNotIEndsWith = '!s.ew.i',
  StringNotISearch = '!s.s.i',

  // StringList
  StringListEquals = 'sl.eq',
  StringListHas = 'sl.h',
  StringListHasEvery = 'sl.he',
  StringListHasSome = 'sl.hs',
  StringListIsEmpty = 'sl.mte',
}

export type FilterOperatorType = `${FilterOperator}`;
