name: Trigger Deploy
description: 'Trigger Deploy'
inputs:
  openshift-server:
    description: 'OpenShift server'
    required: true
  api-token:
    description: 'OpenShift service account API token'
    required: true
  project:
    description: 'Project to redeploy'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Rebuild the image streams
      run: |
        chmod +x ./.github/actions/trigger-deploy/redeploy.sh
        ./.github/actions/trigger-deploy/redeploy.sh "${{ inputs.openshift-server }}" "${{ inputs.api-token }}" '${{ inputs.project }}'
      shell: bash