apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-configmap
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /tmp/log/app.log
      fields:
        log_type: "app"
      processors:
        - decode_json_fields:
            fields: ["message"]
            target: ""
            overwrite_keys: true
            add_error_key: true

    - type: log
      paths:
        - /tmp/log/api.log
      fields:
        log_type: "api"
      processors:
        - decode_json_fields:
            fields: ["message"]
            target: ""
            overwrite_keys: true
            add_error_key: true

    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]
      indices:
        - index: "alexandria-app-log-%{+YYYY.MM.dd}"
          when.contains:
            fields.log_type: "app"
        - index: "alexandria-api-log-%{+YYYY.MM.dd}"
          when.contains:
            fields.log_type: "api"

