kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  DISCOVERY: "https://dev.loginproxy.gov.bc.ca/auth/realms/standard/.well-known/openid-configuration"
  REFRESH_SESSION_INTERVAL: "120"
  ACCESS_TOKEN_EXPIRES_IN: "60"
