apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: es-cluster
    labels:
        "app.kubernetes.io/part-of": ek-stack
spec:
    serviceName: elasticsearch
    replicas: 2
    selector:
        matchLabels:
            app: elasticsearch
    template:
        metadata:
            labels:
                app: elasticsearch
        spec:
            containers:
                - name: elasticsearch
                  resources:
                      requests:
                          cpu: 800m
                          memory: 3Gi
                 