apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nestjs-app
spec:
  to:
    kind: Service
    name: nestjs-app
  port:
    targetPort: 4000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
