
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: api
spec:
  # lookupPolicy:
  #   local: true
  tags:
    - name: develop-latest
      from:
        kind: DockerImage
        name: artifacts.developer.gov.bc.ca/af3c-gen-docker-local/api:develop-latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: stage-latest
      from:
        kind: DockerImage
        name: artifacts.developer.gov.bc.ca/af3c-gen-docker-local/api:stage-latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: latest
      from:
        kind: DockerImage
        name: artifacts.developer.gov.bc.ca/af3c-gen-docker-local/api:latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
