apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: sidecar
spec:
  strategy:
    type: Rolling
  replicas: 1
  selector:
    name: sidecar
  template:
    metadata:
      labels:
        name: sidecar
    spec:
      automountServiceAccountToken: false
      containers:
      - name: sidecar
        image: node:18.17.0
        command: ["node"]
        args: ["-e", "setInterval(() => console.log('Node.js is running'), 1000 * 60 * 60);"]
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: npm_config_cache
          value: "/tmp/.npm"
        envFrom:
        - secretRef:
            name: secrets
        resources:
          requests:
            cpu: 10m 
            memory: 50Mi 
          limits:
            cpu: 50m 
            memory: 100Mi 
