apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: es-cluster
    labels:
        "app.kubernetes.io/part-of": ek-stack
spec:
    serviceName: elasticsearch
    replicas: 2
    selector:
        matchLabels:
            app: elasticsearch
    template:
        metadata:
            labels:
                app: elasticsearch
        spec:
            containers:
                - name: elasticsearch
                  image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
                  resources:
                      limits:
                          cpu: 500m
                          memory: 3Gi
                      requests:
                          cpu: 200m
                          memory: 1.5Gi
                  ports:
                      - name: rest
                        containerPort: 9200
                        protocol: TCP
                      - name: inter-node
                        containerPort: 9300
                        protocol: TCP
                  volumeMounts:
                      - name: elasticsearch-data
                        mountPath: /usr/share/elasticsearch/data
                  env:
                      - name: cluster.name
                        value: elasticsearch
                      - name: node.name
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: discovery.seed_hosts
                        value: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch"
                      - name: cluster.initial_master_nodes
                        value: "es-cluster-0,es-cluster-1"
                      - name: ES_JAVA_OPTS
                        value: "-Xms512m -Xmx512m"
                      - name: xpack.security.enabled
                        value: "false"
                      - name: xpack.security.enrollment.enabled
                        value: "false"
                      - name: ELASTIC_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: secrets
                            key: ELASTIC_PASSWORD
                  volumes:
                  - name: elasticsearch-data
                    persistentVolumeClaim:
                      claimName: elasticsearch-data
                  securityContext:
                        allowPrivilegeEscalation: false
                        runAsNonRoot: true
                        capabilities:
                          drop:
                            - ALL
    volumeClaimTemplates:
        - metadata:
              name: elasticsearch-data
              labels:
                  app: elasticsearch
          spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: netapp-file-standard
              resources:
                  requests:
                      storage: "1Gi"