#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BRANCH=$(git branch | grep '*' | sed 's/* //')
PROTECTED_BRANCHES="^(main|stage|develop)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
    echo "\n🚫 Committing directly to '$BRANCH' is not allowed.  Create a feature branch and commit your work there instead.\n"
    exit 1
fi

npx lint-staged
