version: '3.8'
services:
  vite_docker:
    build:
      context: ../../
      dockerfile: apps/app/Dockerfile
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_KEYCLOAK_REALM_URL=${VITE_KEYCLOAK_REALM_URL}
        - VITE_KEYCLOAK_CLIENT_ID=${VITE_KEYCLOAK_CLIENT_ID}
        - VITE_KEYCLOAK_REDIRECT_URL=${VITE_KEYCLOAK_REDIRECT_URL}
    ports:
      - 5173:5173
    volumes:
      - ./src:/usr/src/app/src
