version: '3.8'
services:
  vite_docker:
    build:
      context: ../../
      dockerfile: apps/app/Dockerfile
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_SUPPORT_EMAIL=${VITE_SUPPORT_EMAIL}
        - VITE_ENV=${VITE_ENV}
    ports:
      - 5173:5173
    volumes:
      - ./src:/usr/src/app/src
