name: Run ACS

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    name: Scan image
    steps:
      - uses: actions/checkout@v2
      # - id: scan
      #   uses: ./.github/actions/stackrox-scan
      #   with:
      #     image: 'alexstruk/api:latest'
      #     central-endpoint: ${{ secrets.ROX_CENTRAL_ENDPOINT }}
      #     api-token: ${{ secrets.ROX_API_TOKEN }}
      # - id: check
      #   uses: ./.github/actions/stackrox-check
      #   with:
      #     image: 'alexstruk/api:latest'
      #     central-endpoint: ${{ secrets.ROX_CENTRAL_ENDPOINT }}
      #     api-token: ${{ secrets.ROX_API_TOKEN }}
      - id: check-api-dc
        uses: ./.github/actions/stackrox-dc-check
        with:
          path: 'deployments/openshift/kustomize/base/api/nestjs/dc.yml'
          central-endpoint: ${{ secrets.ROX_CENTRAL_ENDPOINT }}
          api-token: ${{ secrets.ROX_API_TOKEN }}