name: Unit Tests
on:
  workflow_dispatch:
  push:
    branches:
      - stage

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js with NPM Cache
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Restore Node Modules Cache
        id: cache-node-modules-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Root Dependencies
        if: steps.cache-node-modules-restore.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
        env:
          HUSKY: 0

      - name: Save Node Modules Cache
        if: steps.cache-node-modules-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Run React Tests
        run: npx -w app jest

      - name: Run NestJS Tests
        if: always()
        run: npx -w api jest

      - name: Run common-kit tests
        if: always()
        run: npx -w common-kit jest

      # - name: Upload Test Results
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-results
      #     path: |
      #       apps/app/junit.xml
      #       apps/api/junit.xml
      #       apps/api/coverage
